idf_component_register(
                SRCS
                	main.c
					K_Core/gpio/gpio.c
					K_Core/pcnt/pcnt.c
					K_Core/taskmanager.c
					K_Core/utils/utils.c
					K_Core/serial/serial.c
					K_Core/adc/adc-table.c
					K_Core/adc/adc.c
					K_Core/execution/cmdprocessor.c
					K_core/display/DisplayList.c
					K_core/K_core.c
					L_Core/lcd/lcd.c
                	L_Core/wifi/wifi.c
					L_Core/ble/ble.c
					L_Core/ble/ble-server.c
					L_Core/storage/partition.c
                	L_Core/storage/nvs.c
					L_Core/tone/tone.c
					L_Core/ledc/ledc.c
                	L_Core/ui/ui.c
					L_Core/ui/ui-helpers.c
                    L_Core/ui/ui-splash.c
					L_Core/ui/ui-home.c
					L_Core/ui/ui-control.c
					L_Core/ui/ui-settings.c
					L_Core/ui/ui-diagnostics.c
					L_Core/ui/ui-wifi.c
					L_Core/ui/ui-ble.c
					L_Core/ui/images/hyrel_logo.c
					L_Core/ui/font/en_12.c
                	L_Core/ui/font/en_16.c
                	L_Core/ui/font/en_bold_16.c
                	L_Core/ui/font/en_bold_20.c
                	L_Core/ui/font/en_bold_24.c
                	L_Core/ui/font/en_bold_30.c
                	L_Core/ui/font/mono_bold_16.c
                	L_Core/ui/font/mono_bold_24.c
                	L_Core/ui/font/mono_bold_28.c
                	L_Core/ui/font/mono_bold_32.c
                	L_Core/ui/font/mono_regular_24.c                	
                INCLUDE_DIRS .
					K_Core
					L_Core
                REQUIRES
					nvs_flash
                	lvgl
					m5dial
                	app_update
                	esp_event
                	esp_timer
                	spi_flash
                	esp_partition
                	esp_hw_support
                	bt
                	fatfs
                	sdmmc)
component_compile_options(-fexceptions -x c++ -O0 -Wno-shift-negative-value -Wno-missing-field-initializers -Wno-write-strings -Wno-error=format)
set_property(TARGET ${COMPONENT_TARGET} PROPERTY CXX_STANDARD 17)

